### ISSUE TITLE
get resource group by name

### ISSUE THREAD

**Issue by kyorav** [np-guard/cloud-resource-collector#191]
Check whether we can allow the user to refer to the resource group (in the command line) by name rather than by ID.

**Comment by zivnevo** [comment]
I suggest the following logic:
1. Interpret the user-provided resource group as resource group id, and check if such an id exist using [GetResourceGroup](https://github.com/IBM/platform-services-go-sdk/blob/9b0807ee5a2c82318bf3f1f94ab719f062dca8e1/resourcemanagerv2/resource_manager_v2.go#L312). If it exists, continue using it, as done today.
1. Otherwise, interpret the user-provided resource group as the RG name. Run [ListResourceGroups](https://github.com/IBM/platform-services-go-sdk/blob/9b0807ee5a2c82318bf3f1f94ab719f062dca8e1/resourcemanagerv2/resource_manager_v2.go#L169) and see if there a group with this name. If there is, take its id and use it.
1. Otherwise, return an error
